const { DataTypes } = require('sequelize');
const sequelize = require('../config/db');

/**
 * ReferralCode Model
 * 
 * Stores unique referral codes generated by users
 * Each user can have one referral code per series
 */

const ReferralCode = sequelize.define('ReferralCode', {
  id: {
    type: DataTypes.UUID,
    defaultValue: DataTypes.UUIDV4,
    primaryKey: true,
    allowNull: false
  },
  referralCode: {
    type: DataTypes.STRING(20),
    unique: true,
    allowNull: false,
    field: 'referral_code'
  },
  userId: {
    type: DataTypes.INTEGER,
    allowNull: false,
    field: 'user_id',
    references: {
      model: 'Users',
      key: 'id'
    }
  },
  seriesId: {
    type: DataTypes.UUID,
    allowNull: false,
    field: 'series_id'
  },
  clicksCount: {
    type: DataTypes.INTEGER,
    defaultValue: 0,
    allowNull: false,
    field: 'clicks_count'
  },
  successfulReferrals: {
    type: DataTypes.INTEGER,
    defaultValue: 0,
    allowNull: false,
    field: 'successful_referrals'
  },
  totalEarnings: {
    type: DataTypes.DECIMAL(10, 2),
    defaultValue: 0,
    allowNull: false,
    field: 'total_earnings'
  },
  createdAt: {
    type: DataTypes.DATE,
    allowNull: false,
    defaultValue: DataTypes.NOW,
    field: 'created_at'
  },
  lastUsedAt: {
    type: DataTypes.DATE,
    allowNull: true,
    field: 'last_used_at'
  }
}, {
  tableName: 'referral_codes',
  timestamps: false
});

/**
 * Associations
 */
ReferralCode.associate = (models) => {
  ReferralCode.belongsTo(models.User, {
    foreignKey: 'userId',
    as: 'user'
  });

  ReferralCode.hasMany(models.ReferralCommission, {
    foreignKey: 'referralCode',
    sourceKey: 'referralCode',
    as: 'commissions'
  });
};

module.exports = ReferralCode;
